name: jens
favicon: null
layout_spectrum: 0.7585539715364575
typography_spectrum: 0.006683150306344032
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.05753270094282925
  lightness: 0.16779317590408027
  saturation: 0.9631236910354346
  rhythmicContrast: 0.1295281765051186
purpose: []
